# Generated by Django 6.0.6 on 2026-07-04 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blog_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='featrued_image',
            new_name='featured_image',
        ),
    ]
